### PR TITLE
A few improvements. Feel free to accept/reject/or cherry pick

### PR DESCRIPTION
**Pull request by tupshin**
adds len() to Set, makes the formatting match rustfmt's default style, and a number of improvements to satisfy clippy.

### CODE REVIEW

**Comment by justinsheehy** [comment]
Thanks for the pull request!

This all looks good except for the reformatting changes. If you can resubmit without the 'rustfmt' commit we can cleanly accept it.

I have added https://github.com/justinsheehy/vertree/issues/7 as a result of that commit, as you have helped to point out that we ought to clarify what formatting is desirable. Some of the default rustfmt choices don't work for us, but we should make that clear.

Thanks again.

**Comment by tupshin** [comment]
No problem, I'll respin without the reformatting. 

I am fond of the consistency that rustfmt can apply, and if you describe your differences, I can see if a  rustfmt.toml file might be able to match your style guidelines.

**Comment by andrewjstone** [comment]
@tupshin Turned out it was easier for me to play with rustfmt than try to describe my rules.  I think your other changes are good and should go in. I was especially happy to see that you were able to remove a couple of transmutes with casts. I could not figure out the magic incantation to do that.

**Comment by andrewjstone** [comment]
Fixed by #8 + #9

**Pull request closed without merging**
